version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - /d/media/config/plex:/config
            - /d/media/TV:/data/tvshows
            - /d/media/Movies:/data/movies
        ports:
            - 32469:32469
            - 32400:32400
            - 32401:32401
            - 3005:3005
            - 8324:8324
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plex.localhost
            - VIRTUAL_PORT=32400
        restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /d/media/config/sonarr:/config
            - /d/media/TV:/tv
            - /d/media/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.localhost
            - VIRTUAL_PORT=8989
        restart: always

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /d/media/config/plexpy:/config
            - /d/media/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plexpy.localhost
            - VIRTUAL_PORT=8181
        restart: always

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /d/media/config/nzbhydra:/config
            - /d/media/Downloads:/downloads
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbhydra.localhost
            - VIRTUAL_PORT=5075
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /d/media/config/muximux:/config
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.localhost
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /d/media/config/radarr:/config
            - /d/media/Movies:/movies
            - /d/media/Downloads/complete:/downloads
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.localhost
            - VIRTUAL_PORT=7878
        restart: always

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /d/media/config/ombi:/config
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=ombi.localhost
            - VIRTUAL_PORT=3579
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /d/media/config/nzbget:/config
            - /d/media/Downloads/complete:/complete
            - /d/media/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbget.localhost
            - VIRTUAL_PORT=6789
        restart: always
